# Generated by Django 4.0.6 on 2022-08-07 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100, unique=True)),
                ('tag_desc', models.TextField(blank=True, max_length=300)),
                ('bannerImg', models.ImageField(blank=True, null=True, upload_to='eventBanners/')),
                ('posterImg', models.ImageField(blank=True, null=True, upload_to='eventPosters/')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='events.tags'),
        ),
    ]
