# Generated by Django 4.0.6 on 2022-08-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_tags_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
