# Generated by Django 4.0.6 on 2022-08-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_mediamodel_event_bannerimg_event_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='media',
        ),
        migrations.DeleteModel(
            name='MediaModel',
        ),
    ]
