# Generated by Django 4.0.6 on 2022-08-18 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_blocked_by_account_blocking_account_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='blocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='blocking',
            field=models.ManyToManyField(blank=True, related_name='block', to=settings.AUTH_USER_MODEL),
        ),
    ]
