# Generated by Django 4.0.6 on 2022-08-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_friends_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='friends',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
